name: Lint & Spell Check LaTeX document
on: [push]
jobs:
    lint_and_spell_check_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2

            - name: Lint LaTeX document
              uses: ChiefGokhlayeh/textidote-action@v5
              env:
                allowedwords: ../.github/workflows/allowed-words.txt
              with:
                  root_file: ./docs/proyecto.tex
                  args: --check es --dict $allowedwords

            - name: Upload TeXtidote report
              uses: actions/upload-artifact@v2
              with:
                  name: textidote_report
                  path: report.html

            - name: Throw error if linter warnings exist
              if: ${{ steps.lint.outputs.num_warnings != 0 }}
              run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
